name: Go Auto Test

on:
  push:
    paths:
      - "apitable.go/**"
      - ".github/**"
  pull_request:
    paths:
      - "apitable.go/**"

jobs:

  unit_test:
    defaults:
      run:
        shell: bash
        working-directory: apitable.go
    runs-on: ubuntu-latest
    environment: api
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
        TOKEN: ${{ secrets.TOKEN }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        DATASHEET_ID: ${{ secrets.DATASHEET_ID }}
        VIEW_ID: ${{ secrets.VIEW_ID }}
        NUMBER_FIELD_NAME: ${{ secrets.NUMBER_FIELD_NAME }}
      run: go test -v ./test/...
