name: Java Publish Package

on:
  release:
    paths: 'apitable.java/.version'
    types: [created]
    tags:
      - 'apitable.java@'

jobs:
  publish:
    defaults:
      run:
        shell: bash
        working-directory: apitable.java
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_profiles: 'release-ossrh'
          maven_args: '-DskipTests'
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME}}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}