name: PHP Auto Test

on:
  workflow_dispatch:
  push:
    paths:
      - "apitable.php/**"
      - ".github/workflows/php-test.yml"
    tags:
      - "apitable.php@"
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["**"]
    paths:
      - "apitable.php/**"
      - ".github/workflows/php-test.yml"

defaults:
  run:
    shell: bash
    working-directory: apitable.php

jobs:
  unit_test:
    runs-on: ubuntu-latest
    environment: api
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: apitable.php

      - name: Test
        uses: php-actions/phpunit@v3
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TOKEN: ${{ secrets.TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
          DATASHEET_ID: ${{ secrets.DATASHEET_ID }}
          VIEW_ID: ${{ secrets.VIEW_ID }}
          NUMBER_FIELD_NAME: ${{ secrets.NUMBER_FIELD_NAME }}
        with:
          bootstrap: apitable.php/vendor/autoload.php
          configuration: apitable.php/test/phpunit.xml
