name: Python Publish Package

on:
  push:
    paths: "apitable.py/.version"
    tags:
      - "apitable.py@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          working-directory: ./apitable.py
          poetry-version: 1.5.1
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd apitable.py
          poetry run python setup.py sdist bdist_wheel
          poetry run popipx run twine upload dist/*
