name: Python Auto Test

on:
  push:
    paths:
      - "apitable.py/**"
      - ".github/workflows/py-test.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["**"]
    paths: "apitable.py/**"

jobs:
  unit_test:
    runs-on: ubuntu-latest
    environment: api
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.x"
      - name: Install dependencies
        run: |
          cd apitable.py
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
      - name: just build
        run: |
          cd apitable.py
          python setup.py sdist bdist_wheel
      - name: test
        env:
          DOMAIN: ${{secrets.DOMAIN}}
          TOKEN: ${{secrets.TOKEN}}
          PYTHON_DATASHEET_ID: ${{secrets.PYTHON_DATASHEET_ID}}
          PYTHON_VIEW_ID: ${{secrets.PYTHON_VIEW_ID}}
          SPACE_ID: ${{secrets.SPACE_ID}}
          FOLDER_ID: ${{secrets.FOLDER_ID}}
        run: |
          cd apitable.py
          pip install pytest
          pytest
